apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: lokeshvermaxs/notejam:latest
        envFrom:
          - configMapRef:
              name: notejam-config
        ports:
        - containerPort: 3000
  
        