apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notejam-data-pvc
spec:
  volumeName: notejam-data-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi