apiVersion: v1
kind: PersistentVolume
metadata:
  name: notejam-data-pv
spec:
  claimRef:
    name: notejam-data-pvc
    namespace: default
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
